apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- ingress.yaml

patchesStrategicMerge:
- deployment.yaml

commonLabels:
  environment: production