apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-example
  labels:
    app: k8s-app-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-app-example
  template:
    metadata:
      labels:
        app: k8s-app-example
    spec:
      containers:
      - name: app
        image: ghcr.io/jackycsie/k8s-app-example:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"