apiVersion: v1
kind: Service
metadata:
  name: k8s-app-example
  labels:
    app: k8s-app-example
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: k8s-app-example